url: https://www.madebymeshop.com
baseurl: 

# Site settings
title: Made by Me
email: info@madebymeshop.com
description: "Detalles especiales hechos a mano con mucho amor."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 229E91
  secondary: 3FB1A5
  secondary-dark: 000

# Team names, titles and social links
people:
- name: Naikare Aldama
  pic: 1
  position: Crafter
  social:
    - title: facebook
      url: http://www.facebook.com/madebymeshopcom
    - title: instagram
      url: http://instagram.com/naikart
    - title: envelope
      url: mailto:info@madebymeshop.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: facebook
      url: http://www.facebook.com/madebymeshopcom
    - title: instagram
      url: http://instagram.com/naikart
    - title: envelope
      url: mailto:info@madebymeshop.com

# Postal address (add as many lines as necessary)
address:
  - line: Leioa, Bizkaia
  #- line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty